// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_v1_blocks from "./routes/api/v1/blocks.ts";
import * as $api_v1_network_vitals from "./routes/api/v1/network/vitals.ts";
import * as $api_v1_transactions from "./routes/api/v1/transactions.ts";
import * as $block_hash_ from "./routes/block/[hash].tsx";
import * as $blockchain from "./routes/blockchain.tsx";
import * as $blocks from "./routes/blocks.tsx";
import * as $docs from "./routes/docs.tsx";
import * as $features from "./routes/features.tsx";
import * as $index from "./routes/index.tsx";
import * as $transaction_hash_ from "./routes/transaction/[hash].tsx";
import * as $transactions from "./routes/transactions.tsx";
import * as $BlockDetail from "./islands/BlockDetail.tsx";
import * as $BlockchainIsland from "./islands/BlockchainIsland.tsx";
import * as $BlocksIsland from "./islands/BlocksIsland.tsx";
import * as $ClipboardCopy from "./islands/ClipboardCopy.tsx";
import * as $GoBackArrow from "./islands/GoBackArrow.tsx";
import * as $TransactionDetail from "./islands/TransactionDetail.tsx";
import * as $TransactionsIsland from "./islands/TransactionsIsland.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/v1/blocks.ts": $api_v1_blocks,
    "./routes/api/v1/network/vitals.ts": $api_v1_network_vitals,
    "./routes/api/v1/transactions.ts": $api_v1_transactions,
    "./routes/block/[hash].tsx": $block_hash_,
    "./routes/blockchain.tsx": $blockchain,
    "./routes/blocks.tsx": $blocks,
    "./routes/docs.tsx": $docs,
    "./routes/features.tsx": $features,
    "./routes/index.tsx": $index,
    "./routes/transaction/[hash].tsx": $transaction_hash_,
    "./routes/transactions.tsx": $transactions,
  },
  islands: {
    "./islands/BlockDetail.tsx": $BlockDetail,
    "./islands/BlockchainIsland.tsx": $BlockchainIsland,
    "./islands/BlocksIsland.tsx": $BlocksIsland,
    "./islands/ClipboardCopy.tsx": $ClipboardCopy,
    "./islands/GoBackArrow.tsx": $GoBackArrow,
    "./islands/TransactionDetail.tsx": $TransactionDetail,
    "./islands/TransactionsIsland.tsx": $TransactionsIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
